### PR TITLE
Added kernel modules package support

### PR DESCRIPTION
**Pull request by Tantawi**

### CODE REVIEW

**Comment by mtompkins** [comment]
Appreciate the PR. There was a reason I pulled the modules outside of the packaging and it has been so long I can't remember why. Let me give it a day or two and see if it comes to me. If not I'll gladly merge it.

**Comment by Tantawi** [comment]
Thanks for the great tool!

The reason I added it back was that the installer started to fail from kernel v4.16.4 and up.

Few things more I am looking to fix:

1- How to arrange the kernel list so the latest kernel is always #1 (currently it is usually #2).
2- Add support for release candidate kernels through a specific parameter perhaps.

**Comment by mtompkins** [comment]
#2 may be this https://github.com/mtompkins/linux-kernel-utilities/blob/b78dfb54ce99844f2486c11085ac93d05b14588f/variables#L30

**Comment by mtompkins** [comment]
#1 I'll have to have a look but I think it's correctly ordered for me.

**Comment by Tantawi** [comment]
Now when I removed the -rc filter, kernel list is displayed in correct order. If you have the -rc filter on, kernel 4.16 will show #1, kernel 4.16.5 will show #2, thanks for the tip!

**Comment by mtompkins** [comment]
Can't remember why - merged.

**Pull request merged**
